name: Unzip Files
   on: push
   jobs:
     unzip:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - run: |
             sudo apt-get install unzip -y
             unzip agti.zip -d extracted/
             rm agti.zip
         - uses: actions/github-script@v6
           with:
             script: |
               await github.rest.repos.createOrUpdateFileContents({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 path: 'extracted/README.md',  # Example file
                 message: 'Auto-extracted ZIP',
                 content: Buffer.from('Extracted files').toString('base64')
               })
